info:
  component: Edge Server
  
management:
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
    

zuul:
  prefix: /api
  routes:
    user: 
      path: /auth/**
      serviceId: user-service
    auth: 
      path: /**
      serviceId: security-service
       

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.cognizant.outreach: INFO
  file: api-gateway.log