info:
  component: Edge Server
  
management:
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
    

zuul:
  prefix: /api
  routes:
    security: 
      path: /security/**
      serviceId: security-service
    school: 
      path: /school/**
      serviceId: school-service
    perfdata: 
      path: /perfdata/**
      serviceId: perfdata-service
  host:
    connect-timeout-millis: 100000 ## TODO this need to be changed to 5 secs before prod deployment      

# Enable ribbon as this has a client consumes security service
ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.cognizant.outreach: INFO
  pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: gateway-server.log